version: '2.2'
services:
  es1:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.0
    container_name: es1
    environment:
      - node.name=es1
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es2,es3
      - cluster.initial_master_nodes=es1,es2,es3
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /games/ssd/es/data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic

  es2:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.0
    container_name: es2
    environment:
      - node.name=es2
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es1,es3
      - cluster.initial_master_nodes=es1,es2,es3
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /games/ssd/es/data02:/usr/share/elasticsearch/data
    ports:
      - 9201:9200
    networks:
      - elastic

  es3:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.0
    container_name: es3
    environment:
      - node.name=es3
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es1,es2
      - cluster.initial_master_nodes=es1,es2,es3
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /games/ssd/es/data03:/usr/share/elasticsearch/data
    ports:
      - 9202:9200
    networks:
      - elastic

  db:
    image: postgis/postgis
    shm_size: 10g
    environment:
      POSTGRES_PASSWORD: root
    volumes:
      - /games/ssd/pgdata:/var/lib/postgresql/data

volumes:
  data01:
    driver: local
  data02:
    driver: local
  data03:
    driver: local

networks:
  elastic:
    driver: bridge
